version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: support

  adminer:
    image: adminer
    restart: always
    ports:
      - "8086:8080"

  php-apache:
    container_name: support
    build:
      context: ./php
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/support
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db